// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/jeeo/pack-management/internal/model"
)

// OrderApplication is an autogenerated mock type for the OrderApplication type
type OrderApplication struct {
	mock.Mock
}

// CalculateOrderPack provides a mock function with given fields: _a0, _a1
func (_m *OrderApplication) CalculateOrderPack(_a0 context.Context, _a1 int) ([]model.OrderPack, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CalculateOrderPack")
	}

	var r0 []model.OrderPack
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]model.OrderPack, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []model.OrderPack); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OrderPack)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderApplication creates a new instance of OrderApplication. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderApplication(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderApplication {
	mock := &OrderApplication{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
